name: startup_namer
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning aterence/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1
  firebase_storage: ^10.1.6
  mailer: ^5.1.1
  card_settings: ^3.0.0
  html: ^0.15.0
  excel: ^2.0.0-null-safety
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  file_picker: ^4.0.0
#  flutter_boom_menu: ^1.0.2
  pdf: ^3.8.1
  open_file: ^3.0.1
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  loading_animations: ^2.2.0
  flutter_typeahead: ^4.0.0
  material_dialogs: ^1.1.3
  rxdart: ^0.27.2 # Add this line
  http: ^0.13.0
  csv: ^5.1.1
  meta: ^1.7.0
  contacts_service: ^0.6.3
  url_launcher: ^6.0.20

















dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: "^0.6.1"

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
flutter:
  fonts:
     - family:  MyFlutterApp
       fonts:
        - asset: asset/MyFlutterApp.ttf
  assets:
    - asset/
    - asset/image.jpg
    - asset/mp.webp
  uses-material-design: true
